<div class="popup" id="US-AL">
	<div class="state_name">North Alabama (I-85 North)</div>
	<div class="company_name company_title">Ayers &amp; Associates</div>
	<ul class="rep_list">
		<li><div class="left_title">Address</div><div class="info_right">PO Box 373 <br />Northport, AL 35473</div></li>
		<li><div class="left_title">Name</div><div class="info_right">Mike Ayers</div></li>
		<li><div class="left_title">Office #</div><div class="info_right"> (205) 333-8874</div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="mailto:mike@ayers-associates.com">mike@ayers-associates.com</a></div></li>
	</ul>
	<div class="state_name">South Alabama (I-85 South)</div>
	<div class="company_name company_title">Compass Manufacturing International</div>
	<ul class="rep_list">
		<li><div class="left_title">Address</div><div class="info_right">6702 Enterprise Drive <br />Louisville, Kentucky 40214  </div></li>
		<li><div class="left_title">Toll Free #</div><div class="info_right">(800) 626-3525  </div></li>
		<li><div class="left_title">Phone #</div><div class="info_right"> (502) 367-0222 </div></li>
		<li><div class="left_title">Fax #</div><div class="info_right">(502) 361-0715 </div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="mailto:info@cmiproduct.com">info@cmiproduct.com</a></div></li>
	</ul>
</div>