<div class="popup" id="US-FL">
	<div class="state_name">Florida  - Wholesale</div>
	<div class="company_name company_title">Compass Manufacturing International</div>
	<ul class="rep_list">
		<li><div class="left_title">Address</div><div class="info_right">6702 Enterprise Drive <br />Louisville, Kentucky 40214  </div></li>
		<li><div class="left_title">Toll Free #</div><div class="info_right">(800) 626-3525  </div></li>
		<li><div class="left_title">Phone #</div><div class="info_right"> (502) 367-0222 </div></li>
		<li><div class="left_title">Fax #</div><div class="info_right">(502) 361-0715 </div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="mailto:info@cmiproduct.com">info@cmiproduct.com</a></div></li>
	</ul>
	<div class="state_name">Florida  - Retail</div>
	<div class="company_name company_title">McGinnis &amp; Associates - Retail</div>
	<ul class="rep_list">
		<li><div class="left_title">Name</div><div class="info_right"> David McGinnis </div></li>
		<li><div class="left_title">Address</div><div class="info_right">3022 Colonel Springs Way <br />Fort Mill, South Carolina 29708  </div></li>
		<li><div class="left_title">Phone #</div><div class="info_right"> (704) 905-7850 </div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="mailto:dmrep@fmtc.net">dmrep@fmtc.net</a></div></li>
</div>


