<div class="popup" id="US-GA">
	<div class="state_name">Georgia - Wholesale</div>
	<div class="company_name company_title">McKee-Nix and Associates Inc</div>
	<ul class="rep_list">
		<li><div class="left_title">Address</div><div class="info_right">1844 Tucker Industrial Road <br />Tucker, Georgia 30084  </div></li>
		<li><div class="left_title">Phone #</div><div class="info_right">(770) 934-8061 </div></li>
		<li><div class="left_title">Fax #</div><div class="info_right">(770) 934-3233 </div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="mikeborn@mckeenix.com">mikeborn@mckeenix.com</a></div></li>
	</ul>
	
	<div class="state_name">Georgia  - Retail</div>
	<div class="company_name company_title">McGinnis &amp; Associates - Retail</div>
	<ul class="rep_list">
		<li><div class="left_title">Name</div><div class="info_right"> David McGinnis </div></li>
		<li><div class="left_title">Address</div><div class="info_right">3022 Colonel Springs Way <br />Fort Mill, South Carolina 29708  </div></li>
		<li><div class="left_title">Phone #</div><div class="info_right"> (704) 905-7850 </div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="mailto:dmrep@fmtc.net">dmrep@fmtc.net</a></div></li>
</div>