<div class="popup" id="US-HI">
	<div class="state_name">Hawaii</div>
	<div class="company_name company_title">Compass Manufacturing International</div>
	<ul class="rep_list">
		<li><div class="left_title">Address</div><div class="info_right">6702 Enterprise Drive <br />Louisville, Kentucky 40214  </div></li>
		<li><div class="left_title">Toll Free #</div><div class="info_right">(800) 626-3525  </div></li>
		<li><div class="left_title">Phone #</div><div class="info_right"> (502) 367-0222 </div></li>
		<li><div class="left_title">Fax #</div><div class="info_right">(502) 361-0715 </div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="mailto:info@cmiproduct.com">info@cmiproduct.com</a></div></li>
	</ul>
</div>