<div class="popup" id="US-LA">
	<div class="state_name">Louisiana - Wholesale</div>
	<div class="company_name company_title">Compass Manufacturing International</div>
	<ul class="rep_list">
		<li><div class="left_title">Address</div><div class="info_right">6702 Enterprise Drive <br />Louisville, Kentucky 40214  </div></li>
		<li><div class="left_title">Toll Free #</div><div class="info_right">(800) 626-3525  </div></li>
		<li><div class="left_title">Phone #</div><div class="info_right"> (502) 367-0222 </div></li>
		<li><div class="left_title">Fax #</div><div class="info_right">(502) 361-0715 </div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="mailto:info@cmiproduct.com">info@cmiproduct.com</a></div></li>
	</ul>
	
	<div class="state_name">Louisiana - Retail</div>
	<div class="company_name company_title">Hennen &amp; Associates</div>
	<ul class="rep_list">
		<li><div class="left_title">Name</div><div class="info_right">John Hennen Jr.</div></li>
		<li><div class="left_title">Address</div><div class="info_right">10581 County Road 2300 <br />Quinlan, TX   75474  </div></li>
		<li><div class="left_title">Phone #</div><div class="info_right"> (903) 356-3775 </div></li>
		<li><div class="left_title">Fax #</div><div class="info_right">(903) 356-3855 </div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="mailto:jahennen@msn.com">jahennen@msn.com</a></div></li>
	</ul>
</div>