<div class="popup" id="US-MI">
	<div class="state_name">Michigan</div>
	<div class="company_name company_title">Progressive Marketing</div>
	<ul class="rep_list">
		<li><div class="left_title">Name</div><div class="info_right">Jim Lang - Main Office</div></li>
		<li><div class="left_title">Address</div><div class="info_right">56 Library Street <br />Hudson, OH 44236</div></li>
		<li><div class="left_title">Phone # / Fax</div><div class="info_right"> (330) 656-9389 </div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="mailto:jlang@progressive-marketing.com">jlang@progressive-marketing.com</a></div></li>
		<li><div class="left_title">Name</div><div class="info_right">Paul Cummings</div></li>
		<li><div class="left_title">Phone #</div><div class="info_right">(419) 874-0758 </div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="Paulcummings123@hotmail.com">Paulcummings123@hotmail.com</a></div></li>
		<li><div class="left_title">Name</div><div class="info_right">Jim Hendrickson</div></li>
		<li><div class="left_title">Phone #</div><div class="info_right">(330) 656-9389</div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="Jhendricks123@aol.com">Jhendricks123@aol.com</a></div></li>
		<li><div class="left_title">Name</div><div class="info_right">Jay Stoffner</div></li>
		<li><div class="left_title">Phone #</div><div class="info_right">(231) 334-7600 </div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="jaystoffner@progressive-marketing.com">jaystoffner@progressive-marketing.com</a></div></li>
		<li><div class="left_title">Name</div><div class="info_right">Denny Lang</div></li>
		<li><div class="left_title">Phone #</div><div class="info_right">(724) 744-4996 </div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="dlang@progressive-marketing.com">dlang@progressive-marketing.com</a></div></li>
	</ul>
</div>