<div class="popup" id="US-NJ">
	<div class="state_name">New Jersey - Wholesale</div>
	<div class="company_name">Benedict Enterprises LLC</div>
	<ul class="rep_list">
		<li><div class="left_title">Name</div><div class="info_right">Ben Suleski</div></li>
		<li><div class="left_title">Office #</div><div class="info_right"> (732) 233-6965</div></li>
		<li><div class="left_title">Fax #</div><div class="info_right">(732) 229-0103</div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="mailto:bensuleski@yahoo.com">bensuleski@yahoo.com</a></div></li>
	</ul>
	
	<div class="state_name">New Jersey  - Retail</div>
	<div class="company_name company_title">McGinnis &amp; Associates - Retail</div>
	<ul class="rep_list">
		<li><div class="left_title">Name</div><div class="info_right"> David McGinnis </div></li>
		<li><div class="left_title">Address</div><div class="info_right">3022 Colonel Springs Way <br />Fort Mill, South Carolina 29708  </div></li>
		<li><div class="left_title">Phone #</div><div class="info_right"> (704) 905-7850 </div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="mailto:dmrep@fmtc.net">dmrep@fmtc.net</a></div></li>
</div>