<div class="popup" id="US-PA">
	<div class="state_name">Western, PA to State College, PA</div>
	<div class="company_name company_title">Progressive Marketing - Wholesale &amp; Retail</div>
	<ul class="rep_list">
		<li><div class="left_title">Name</div><div class="info_right">Jim Lang - Main Office</div></li>
		<li><div class="left_title">Address</div><div class="info_right">56 Library Street <br />Hudson, OH 44236</div></li>
		<li><div class="left_title">Phone # / Fax</div><div class="info_right"> (330) 656-9389 </div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="mailto:jlang@progressive-marketing.com">jlang@progressive-marketing.com</a></div></li>
		
		<li><div class="left_title">Name</div><div class="info_right">Jim Hendrickson</div></li>
		<li><div class="left_title">Phone #</div><div class="info_right">(330) 656-9389</div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="Jhendricks123@aol.com">Jhendricks123@aol.com</a></div></li>
		<li><div class="left_title">Name</div><div class="info_right">Jay Stoffner</div></li>
		<li><div class="left_title">Phone #</div><div class="info_right">(231) 334-7600 </div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="jaystoffner@progressive-marketing.com">jaystoffner@progressive-marketing.com</a></div></li>
		<li><div class="left_title">Name</div><div class="info_right">Denny Lang</div></li>
		<li><div class="left_title">Phone #</div><div class="info_right">(724) 744-4996 </div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="dlang@progressive-marketing.com">dlang@progressive-marketing.com</a></div></li>
	</ul>
	<div class="state_name">Eastern PA  - Retail</div>
	<div class="company_name company_title">McGinnis &amp; Associates - Retail</div>
	<ul class="rep_list">
		<li><div class="left_title">Name</div><div class="info_right"> David McGinnis </div></li>
		<li><div class="left_title">Address</div><div class="info_right">3022 Colonel Springs Way <br />Fort Mill, South Carolina 29708  </div></li>
		<li><div class="left_title">Phone #</div><div class="info_right"> (704) 905-7850 </div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="mailto:dmrep@fmtc.net">dmrep@fmtc.net</a></div></li>
	<div class="state_name">All other Areas</div>
	<div class="company_name company_title">Compass Manufacturing International</div>
	<ul class="rep_list">
		<li><div class="left_title">Address</div><div class="info_right">6702 Enterprise Drive <br />Louisville, Kentucky 40214  </div></li>
		<li><div class="left_title">Toll Free #</div><div class="info_right">(800) 626-3525  </div></li>
		<li><div class="left_title">Phone #</div><div class="info_right"> (502) 367-0222 </div></li>
		<li><div class="left_title">Fax #</div><div class="info_right">(502) 361-0715 </div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="mailto:info@cmiproduct.com">info@cmiproduct.com</a></div></li>
	</ul>
</div>