<div class="popup" id="US-SC">
	<div class="state_name">South Carolina - Wholesale</div>
	<div class="company_name company_title">ARC - Associated Representative Carolina</div>
	<ul class="rep_list">
		<li><div class="left_title">Name</div><div class="info_right"> Harry Goble</div></li>
		<li><div class="left_title">Address</div><div class="info_right">103 Oakwood Place<br />Hendersonville, NC 28792</div>
		<li><div class="left_title">Phone # / Fax</div><div class="info_right"> (828) 595-3677 </div></li>
		<li><div class="left_title">Cell #</div><div class="info_right"> (704) 692-0241 </div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="mailto:harry-arc@live.com">harry-arc@live.com</a></div></li>
	</ul>
	<ul class="rep_list">
		<li><div class="left_title">Name</div><div class="info_right"> Danny Dixon</div></li>
		<li><div class="left_title">Address</div><div class="info_right">18 Valleywood Court <br/>Asheville, NC 28803</div>
		<li><div class="left_title">Phone #</div><div class="info_right">(828) 551-1062 </div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="mailto:danny-arc@live.com">danny-arc@live.com</a></div></li>
	</ul>
	
	<div class="state_name">South Carolina  - Retail</div>
	<div class="company_name company_title">McGinnis &amp; Associates - Retail</div>
	<ul class="rep_list">
		<li><div class="left_title">Name</div><div class="info_right"> David McGinnis </div></li>
		<li><div class="left_title">Address</div><div class="info_right">3022 Colonel Springs Way <br />Fort Mill, South Carolina 29708  </div></li>
		<li><div class="left_title">Phone #</div><div class="info_right"> (704) 905-7850 </div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="mailto:dmrep@fmtc.net">dmrep@fmtc.net</a></div></li>
</div>