<div class="popup" id="US-TX">
	<div class="state_name">Waco, Texas - South - Wholesale</div>
	<div class="company_name company_title">Mena Associates Agency</div>
	<ul class="rep_list">
		<li><div class="left_title">Address</div><div class="info_right">802 Dominion Drive Suite 100<br />Katy, TX 77450</div></li>
		<li><div class="left_title">Name</div><div class="info_right">Duane Mena</div></li>
		<li><div class="left_title">Office #</div><div class="info_right"> (281) 579-8228</div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="mailto:dmena@menassociates.com">dmena@menassociates.com</a></div></li>
	</ul>
	<div class="state_name">Central &amp; East Texas - Retail</div>
	<div class="company_name company_title">Hennen &amp; Associates</div>
	<ul class="rep_list">
		<li><div class="left_title">Name</div><div class="info_right">John Hennen Jr.</div></li>
		<li><div class="left_title">Address</div><div class="info_right">10581 County Road 2300 <br />Quinlan, TX   75474  </div></li>
		<li><div class="left_title">Phone #</div><div class="info_right"> (903) 356-3775 </div></li>
		<li><div class="left_title">Fax #</div><div class="info_right">(903) 356-3855 </div></li>
		<li><div class="left_title">Email</div><div class="info_right"><a href="mailto:jahennen@msn.com">jahennen@msn.com</a></div></li>
	</ul>
</div>